version: '3.1'

services:

  review:
    image: review-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7070:7070"
    networks:
      - review
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo:27017
      - SPRING_DATA_MONGODB_DATABASE=reviews

  mongo:
    image: mongo
    restart: always
    hostname: mongo
    networks:
      - review
    volumes:
      - mongo_data:/data/db
    ports:
    - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - review
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

volumes:
  mongo_data:

networks:
  review:
    driver: bridge